### ISSUE TITLE
i have to ask a Question: can i port the code as a bukkit plugin(Asking due to you may DMCA my bukkit port if i don't get approve from you.)

### ISSUE THREAD

**Issue by Outfit8TSB** [Lenni0451/ViaProxyMultiLaunch#2]
can i port the code as a bukkit plugin? this viaproxy plugin deserves to be bukkit plugin, it would be useful in case the computer they can't run 2 processes at once like the server computer of minecraft hosting provider.

however, i have considered a legal problem, like the DMCA, so i shall kindly ask for approval of using your code.

(i know this is issue panel, but i have to ask in there, as there is no discussion panel of ViaVersion Addons. i was wanted to use this plugin in bukkit after i started to use hosting provider. in fact, most bukkit plugins(like worldedit, luckperms) provide porting.)

**Comment by Lenni0451** [comment]
Hi, that is absolutely no problem for me. Feel free to port this plugin to any platform you want.
It would be nice if you could credit me for the original code base tho.

**Comment by Outfit8TSB** [comment]
thank you!
